# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marta/Pobrane/ProjektSemestralnyTestowanie/ProjektSemestralnyTestowanie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marta/Pobrane/ProjektSemestralnyTestowanie/ProjektSemestralnyTestowanie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marta/Pobrane/ProjektSemestralnyTestowanie/ProjektSemestralnyTestowanie/CMakeFiles /home/marta/Pobrane/ProjektSemestralnyTestowanie/ProjektSemestralnyTestowanie/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marta/Pobrane/ProjektSemestralnyTestowanie/ProjektSemestralnyTestowanie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjektSemestralnyTestowanie

# Build rule for target.
ProjektSemestralnyTestowanie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProjektSemestralnyTestowanie
.PHONY : ProjektSemestralnyTestowanie

# fast build rule for target.
ProjektSemestralnyTestowanie/fast:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/build
.PHONY : ProjektSemestralnyTestowanie/fast

Clock.o: Clock.cpp.o

.PHONY : Clock.o

# target to build an object file
Clock.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Clock.cpp.o
.PHONY : Clock.cpp.o

Clock.i: Clock.cpp.i

.PHONY : Clock.i

# target to preprocess a source file
Clock.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Clock.cpp.i
.PHONY : Clock.cpp.i

Clock.s: Clock.cpp.s

.PHONY : Clock.s

# target to generate assembly for a file
Clock.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Clock.cpp.s
.PHONY : Clock.cpp.s

Compare.o: Compare.cpp.o

.PHONY : Compare.o

# target to build an object file
Compare.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Compare.cpp.o
.PHONY : Compare.cpp.o

Compare.i: Compare.cpp.i

.PHONY : Compare.i

# target to preprocess a source file
Compare.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Compare.cpp.i
.PHONY : Compare.cpp.i

Compare.s: Compare.cpp.s

.PHONY : Compare.s

# target to generate assembly for a file
Compare.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Compare.cpp.s
.PHONY : Compare.cpp.s

Event.o: Event.cpp.o

.PHONY : Event.o

# target to build an object file
Event.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Event.cpp.o
.PHONY : Event.cpp.o

Event.i: Event.cpp.i

.PHONY : Event.i

# target to preprocess a source file
Event.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Event.cpp.i
.PHONY : Event.cpp.i

Event.s: Event.cpp.s

.PHONY : Event.s

# target to generate assembly for a file
Event.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Event.cpp.s
.PHONY : Event.cpp.s

EventsQueue.o: EventsQueue.cpp.o

.PHONY : EventsQueue.o

# target to build an object file
EventsQueue.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/EventsQueue.cpp.o
.PHONY : EventsQueue.cpp.o

EventsQueue.i: EventsQueue.cpp.i

.PHONY : EventsQueue.i

# target to preprocess a source file
EventsQueue.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/EventsQueue.cpp.i
.PHONY : EventsQueue.cpp.i

EventsQueue.s: EventsQueue.cpp.s

.PHONY : EventsQueue.s

# target to generate assembly for a file
EventsQueue.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/EventsQueue.cpp.s
.PHONY : EventsQueue.cpp.s

Linia.o: Linia.cpp.o

.PHONY : Linia.o

# target to build an object file
Linia.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Linia.cpp.o
.PHONY : Linia.cpp.o

Linia.i: Linia.cpp.i

.PHONY : Linia.i

# target to preprocess a source file
Linia.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Linia.cpp.i
.PHONY : Linia.cpp.i

Linia.s: Linia.cpp.s

.PHONY : Linia.s

# target to generate assembly for a file
Linia.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Linia.cpp.s
.PHONY : Linia.cpp.s

Person.o: Person.cpp.o

.PHONY : Person.o

# target to build an object file
Person.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Person.cpp.o
.PHONY : Person.cpp.o

Person.i: Person.cpp.i

.PHONY : Person.i

# target to preprocess a source file
Person.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Person.cpp.i
.PHONY : Person.cpp.i

Person.s: Person.cpp.s

.PHONY : Person.s

# target to generate assembly for a file
Person.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Person.cpp.s
.PHONY : Person.cpp.s

Simulation.o: Simulation.cpp.o

.PHONY : Simulation.o

# target to build an object file
Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Simulation.cpp.o
.PHONY : Simulation.cpp.o

Simulation.i: Simulation.cpp.i

.PHONY : Simulation.i

# target to preprocess a source file
Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Simulation.cpp.i
.PHONY : Simulation.cpp.i

Simulation.s: Simulation.cpp.s

.PHONY : Simulation.s

# target to generate assembly for a file
Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Simulation.cpp.s
.PHONY : Simulation.cpp.s

Stop.o: Stop.cpp.o

.PHONY : Stop.o

# target to build an object file
Stop.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Stop.cpp.o
.PHONY : Stop.cpp.o

Stop.i: Stop.cpp.i

.PHONY : Stop.i

# target to preprocess a source file
Stop.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Stop.cpp.i
.PHONY : Stop.cpp.i

Stop.s: Stop.cpp.s

.PHONY : Stop.s

# target to generate assembly for a file
Stop.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Stop.cpp.s
.PHONY : Stop.cpp.s

Tram.o: Tram.cpp.o

.PHONY : Tram.o

# target to build an object file
Tram.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Tram.cpp.o
.PHONY : Tram.cpp.o

Tram.i: Tram.cpp.i

.PHONY : Tram.i

# target to preprocess a source file
Tram.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Tram.cpp.i
.PHONY : Tram.cpp.i

Tram.s: Tram.cpp.s

.PHONY : Tram.s

# target to generate assembly for a file
Tram.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Tram.cpp.s
.PHONY : Tram.cpp.s

Vehicle.o: Vehicle.cpp.o

.PHONY : Vehicle.o

# target to build an object file
Vehicle.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Vehicle.cpp.o
.PHONY : Vehicle.cpp.o

Vehicle.i: Vehicle.cpp.i

.PHONY : Vehicle.i

# target to preprocess a source file
Vehicle.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Vehicle.cpp.i
.PHONY : Vehicle.cpp.i

Vehicle.s: Vehicle.cpp.s

.PHONY : Vehicle.s

# target to generate assembly for a file
Vehicle.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/Vehicle.cpp.s
.PHONY : Vehicle.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ProjektSemestralnyTestowanie.dir/build.make CMakeFiles/ProjektSemestralnyTestowanie.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ProjektSemestralnyTestowanie"
	@echo "... Clock.o"
	@echo "... Clock.i"
	@echo "... Clock.s"
	@echo "... Compare.o"
	@echo "... Compare.i"
	@echo "... Compare.s"
	@echo "... Event.o"
	@echo "... Event.i"
	@echo "... Event.s"
	@echo "... EventsQueue.o"
	@echo "... EventsQueue.i"
	@echo "... EventsQueue.s"
	@echo "... Linia.o"
	@echo "... Linia.i"
	@echo "... Linia.s"
	@echo "... Person.o"
	@echo "... Person.i"
	@echo "... Person.s"
	@echo "... Simulation.o"
	@echo "... Simulation.i"
	@echo "... Simulation.s"
	@echo "... Stop.o"
	@echo "... Stop.i"
	@echo "... Stop.s"
	@echo "... Tram.o"
	@echo "... Tram.i"
	@echo "... Tram.s"
	@echo "... Vehicle.o"
	@echo "... Vehicle.i"
	@echo "... Vehicle.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

